GLMMS/GLMMS_main/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

# Use include() to add URLS from the catalog application and authentication system
from django.urls import include

urlpatterns += [
    path('catalog/', include('catalog.urls')),
	path('member/', include('member.urls')),
	path('event/', include('event.urls')),
	path('announcement/', include('announcement.urls')),
]

# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
]

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

#add media file support
from . import settings as mysettings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(mysettings.MEDIA_URL, document_root=mysettings.MEDIA_ROOT)

GLMMS/announcement/urls.py
#Author: Jason Pulis

from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'announcement'
urlpatterns = [
    path('announcement', views.AnnouncementsView, name='AnnouncementsView'),
    path('announcement/search/', views.AnnouncementsViewSearch, name='AnnouncementsViewSearch'),
    path('announcement/<int:pk>/', views.announcement_detail, name='announcement_detail'),
    path('announcement/new', views.announcement_new, name='announcement_new'),
    path('announcement/<int:pk>/edit/', views.announcement_edit, name='announcement_edit'),
    path('announcement/<int:pk>/delete/', views.announcement_delete, name='announcement_delete'),
    path('announcement/<int:pk>/deleteComment/', views.comment_delete, name='comment_delete'),
    url(r'^search/$', views.search, name='search'),
    url(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_announcement, name='add_comment_to_announcement'),
]

GLMMS/event/urls.py
#Author: Christopher Whetsel

from django.urls import path

from . import views

app_name = 'event'
urlpatterns = [
    path('', views.events_view, name='events_view'),
    path('event/past/', views.past_events_view, name="past_events"),
    path('event/<int:pk>/', views.event_detail, name='event_detail'),
    path('event/new/', views.event_new, name='event_new'),
    path('event/<int:pk>/edit/', views.event_edit, name='event_edit'),
    path('event/<int:pk>/rsvp/', views.event_rsvp, name='event_rsvp'),
    path('event/<int:pk>/delete/', views.event_delete, name='event_delete'),
    path('event/<int:pk>/notify/', views.event_notify, name='event_notify'),
]

GLMMS/locallibrary/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

# Use include() to add URLS from the catalog application and authentication system
from django.urls import include

urlpatterns += [
    path('catalog/', include('catalog.urls')),
	path('member/', include('member.urls')),
	path('event/', include('event.urls')),
	path('announcement/', include('announcement.urls')),
]

# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
]

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

#add media file support
from . import settings as mysettings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
 
 
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(mysettings.MEDIA_URL, document_root=mysettings.MEDIA_ROOT)

GLMMS/member/urls.py
#Author: Christopher Whetsel

'''this file defines the mapping of urls to view functions. see views.py for the view definitions.'''
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'member'
urlpatterns = [
	path('search', views.search_index, name='search_index'),
	path('search/single/', views.single_search, name='single_search'),
	path('search/multi/', views.multi_search, name='multi_search'),
	path('search/job/', views.job_search, name='job_search'),
	path('search/position/', views.position_search, name='position_search'),
	path('search/organization/', views.org_search, name='organization_search'),
	path('profile/<int:pk>/', login_required(views.ProfileDetailView.as_view()), name='profile'),
	path('profile/edit/<int:profile_id>', views.edit_info, name='edit_profile'),
]

'''urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
	path('<int:pk>/', views.SingleDetailView.as_view(), name='single_detail'),
	path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
	path('<int:question_id>/vote/', views.vote, name='vote'),
]'''

GLMMS/templates/common/base.html
<!--
Co-Authors: Christopher Whetsel, Jason Pulis
Formating: Mike Winkelmann
-->

<!DOCTYPE html>
<html lang="en">
<head>

  {% block title %} <title>GLMMS</title> {% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="icon" href="{% static 'catalog/images/coat.png' %}">
  <link rel="stylesheet" href="{% static 'catalog/css/styles.css' %}">
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'index' %}">GLMMS</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      {% if user.is_authenticated %}
      <ul class="navbar-nav mr-auto">
        <li><a class="nav-link" href="{% url 'member:search_index' %}">Member Search</a></li>
        <li><a class="nav-link" href="{% url 'announcement:AnnouncementsView' %}">Announcements</a></li>
        <li><a class="nav-link" href="{% url 'event:events_view' %}">Events</a></li>
      </ul>
      <li class="nav-item dropdown" id="loginDropdown">
        <a class="btn btn-outline-danger nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Welcome, {{ user.get_username }}!
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'member:profile' user.profile.id %}">Your Profile</a>
          <a class="dropdown-item" href="{% url 'logout'%}?next={{request.path}}">Logout</a>
        </div>
      </li>
      {% else %}
      <ul class="navbar-nav ml-auto">
        <li><a class="btn btn-outline-danger" href="{% url 'login'%}?next={{request.path}}">Login</a></li>
      </ul>
      {% endif %}
    </div>
  </nav>

<div class="container-fluid">

<div class="row" style="padding:20px">
  <div class="col-sm-12 ">
  {% block content %}{% endblock %}

  {% block pagination %}
    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
  {% endblock %}


  </div>
</div>

</div>
</body>
</html>