GLMMS/GLMMS_main/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

# Use include() to add URLS from the catalog application and authentication system
from django.urls import include

urlpatterns += [
    path('catalog/', include('catalog.urls')),
	path('member/', include('member.urls')),
	path('event/', include('event.urls')),
	path('announcement/', include('announcement.urls')),
]

# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
]

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

#add media file support
from . import settings as mysettings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(mysettings.MEDIA_URL, document_root=mysettings.MEDIA_ROOT)

GLMMS/announcement/urls.py
#Author: Jason Pulis

from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'announcement'
urlpatterns = [
    path('announcement', views.AnnouncementsView, name='AnnouncementsView'),
    path('announcement/search/', views.AnnouncementsViewSearch, name='AnnouncementsViewSearch'),
    path('announcement/<int:pk>/', views.announcement_detail, name='announcement_detail'),
    path('announcement/new', views.announcement_new, name='announcement_new'),
    path('announcement/<int:pk>/edit/', views.announcement_edit, name='announcement_edit'),
    path('announcement/<int:pk>/delete/', views.announcement_delete, name='announcement_delete'),
    path('announcement/<int:pk>/deleteComment/', views.comment_delete, name='comment_delete'),
    url(r'^search/$', views.search, name='search'),
    url(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_announcement, name='add_comment_to_announcement'),
]

GLMMS/event/urls.py
#Author: Christopher Whetsel

from django.urls import path

from . import views

app_name = 'event'
urlpatterns = [
    path('', views.events_view, name='events_view'),
    path('event/past/', views.past_events_view, name="past_events"),
    path('event/<int:pk>/', views.event_detail, name='event_detail'),
    path('event/new/', views.event_new, name='event_new'),
    path('event/<int:pk>/edit/', views.event_edit, name='event_edit'),
    path('event/<int:pk>/rsvp/', views.event_rsvp, name='event_rsvp'),
    path('event/<int:pk>/delete/', views.event_delete, name='event_delete'),
    path('event/<int:pk>/notify/', views.event_notify, name='event_notify'),
]

GLMMS/locallibrary/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

# Use include() to add URLS from the catalog application and authentication system
from django.urls import include

urlpatterns += [
    path('catalog/', include('catalog.urls')),
	path('member/', include('member.urls')),
	path('event/', include('event.urls')),
	path('announcement/', include('announcement.urls')),
]

# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
]

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

#add media file support
from . import settings as mysettings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
 
 
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(mysettings.MEDIA_URL, document_root=mysettings.MEDIA_ROOT)

GLMMS/announcement/models.py
#Author: Christopher Whetsel

from django.db import models
from django.conf import settings
import datetime

from member.models import Profile
# Create your models here.
class Announcement(models.Model):
	GENERAL = 'A'
	SOCIAL = 'B'
	PROFESSIONAL = 'C'
	PHILANTHROPY = 'D'
	RECRUITMENT = 'E'
	NEWMEMBER = 'F'
	NORMAL = 'G'
	URGENT = 'H'
	TYPES = ((NORMAL, 'Normal'), (URGENT, 'Urgent'),)
	TOPICS = ((GENERAL, 'General'), (SOCIAL,'Social'), (PROFESSIONAL, 'Professional'), (PHILANTHROPY, 'Philanthropy'), (RECRUITMENT, 'Recruitment'), (NEWMEMBER, 'New Member'),)
										#Profile
	creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	title = models.CharField(max_length=63)
	topic = models.CharField(max_length=1, choices=TOPICS, default=GENERAL)
	type = models.CharField(max_length=1, choices=TYPES, default=NORMAL)
	message = models.TextField()
	dateAdded = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.title

class Comment(models.Model):
    post = models.ForeignKey('announcement.Announcement', on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    text = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
	#change approved to false to enable admin authorization to show comment
    approved_comment = models.BooleanField(default=True)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text

GLMMS/announcement/forms.py
#Author: Jason Pulis

from django import forms
from django.contrib.auth.models import User

from .models import Announcement, Comment

class AnnouncementForm(forms.ModelForm):
	'''This class provides an announcement creation form.'''
	class Meta:
		model = Announcement
		fields = ['type', 'topic', 'title', 'message']

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('text',)

GLMMS/announcement/views.py
#Author: Jason Pulis

from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.views import generic
from django.utils import timezone
from django import forms
from django.contrib.auth.decorators import login_required
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.core.mail import send_mail
from django.contrib import messages
from .filters import AnnouncementFilter

from .models import Announcement, Comment
from .forms import AnnouncementForm, CommentForm
from member.models import Profile
from django.contrib.auth.models import User

# Create your views here.

@login_required
def AnnouncementsView(request):
    announcements_list = Announcement.objects.order_by('-dateAdded')
    paginator = Paginator(announcements_list, 6) # Show 5 announcements per page

    page = request.GET.get('page')
    announcements = paginator.get_page(page)
    return render(request, 'announcement/announcement_view_all.html', {'announcements': announcements})

@login_required
def AnnouncementsViewSearch(request):
    announc= Announcement.objects.all().order_by('-dateAdded')
    filter = AnnouncementFilter(request.GET, queryset = announc)
    return render(request, 'announcement/announcement_search.html', {'filter':filter})

@login_required
def announcement_detail(request, pk):

    announcement = get_object_or_404(Announcement, pk=pk)
    return render(request, 'announcement/announcement_detail.html', {'announcement': announcement})

@login_required
def announcement_new(request):
    #member_list = Profile.objects.filter(member_status="A")
    #print(member_list)

    if request.method == "POST":
        form = AnnouncementForm(request.POST)
        if form.is_valid():
            announcement = form.save(commit=False)
            announcement.creator = request.user
            sender = announcement.creator.email
            announcement.save()
            if announcement.type == "H":
                subject = form.cleaned_data['title']
                message = form.cleaned_data['message']
                send_mail_from = "sender"

                recipients = []
                for profile in Profile.objects.filter(member_status="A"):
                    recipients.append(profile.phone + "@" + profile.cell_carrier_id.sms_address)
                #for user in User.objects.all():
                #    recipients.append(user.email)

                send_mail(subject, message, sender, recipients)
            return redirect('announcement:announcement_detail', pk=announcement.pk)
    else:
        form = AnnouncementForm()
    return render(request, 'announcement/announcement_edit.html', {'form': form})

@login_required
def announcement_edit(request, pk):
    announcement = get_object_or_404(Announcement, pk=pk)
    if request.method == "POST":
        form = AnnouncementForm(request.POST, instance=announcement)
        if form.is_valid():
            announcement = form.save(commit=False)
            announcement.creator = request.user
            announcement.dateAdded = timezone.now()
            announcement.save()
            return redirect('announcement:announcement_detail', pk=announcement.pk)
    else:
        form = AnnouncementForm(instance=announcement)
    return render(request, 'announcement/announcement_edit.html', {'form': form})

@login_required
def announcement_delete(request, pk):
    announcement = get_object_or_404(Announcement, pk=pk)
    if request.user == announcement.creator:
        Announcement.objects.filter(pk=pk).delete()
        messages.add_message(request, messages.INFO, "Announcement Deleted.")
    else:
        messages.add_message(request, messages.INFO, "You cannot delete an announcement you did not create.")
    return redirect('announcement:AnnouncementsView')

@login_required
def search(request):
    announcement_list = Announcement.objects.all()
    announcement_filter = AnnouncementFilter(request.GET, queryset=announcement_list)
    return render(request, 'search/announcement_view_all.html', {'filter': announcement_filter})

@login_required
def add_comment_to_announcement(request, pk):
    announcement = get_object_or_404(Announcement, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.post = announcement
            comment.save()
            return redirect('announcement:announcement_detail', pk=announcement.pk)
    else:
        form = CommentForm()
    return render(request, 'announcement/add_comment_to_announcement.html', {'form': form})

@login_required
def comment_delete(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    if request.user == comment.author:
        Comment.objects.filter(pk=pk).delete()
        messages.add_message(request, messages.INFO, "Comment Deleted.")
    else:
        messages.add_message(request, messages.INFO, "You cannot delete a comment you did not create.")
    return redirect('announcement:announcement_detail', pk=comment.post.pk)

GLMMS/announcement/templates/announcement/add_comment_to_announcement.html
<!-- 
Author: Jason Pulis
Styling: Mike Winkelmann

 -->

{% extends 'common/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h1>New Comment</h1>
    <hr>
    <form method="POST" class="post-form">
        {% csrf_token %}
        <div class="row">
            <div class="col-sm-12 col-lg-6">
                {{ form.text|as_crispy_field }}
            </div>
        </div>

        <a class="btn btn-dark" href="{% url 'announcement:AnnouncementsView' %}">Back</a>
        <button type="submit" class="save btn btn-danger">Send</button>
    </form>
{% endblock %}

GLMMS/announcement/templates/announcement/announcement_detail.html
<!-- 
Author: Jason Pulis
Styling: Mike Winkelmann

 -->

{# This template displays a detailed view of a selected announcement. #}

{% extends 'common/base.html' %}

{% block content %}
{% if messages %}
  <ul class="messages">
      {% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
  </ul>
{% endif %}
    <div class="card">
      <h2 class="card-header">{{ announcement.title }}</h2>
      <div class="card-body">
        <h5 class="class-title">
          Creator: {{ announcement.creator }} on {{ announcement.dateAdded }}
        </h5>
        <div class="class-text">
          <!-- if to convert internal topic codes to readable format -->
          {% if announcement.topic == 'A' %}
          <p> Topic: General </p>
          {% elif announcement.topic == 'B' %}
          <p> Topic: Social </p>
          {% elif announcement.topic == 'C' %}
          <p> Topic: Professional </p>
          {% elif announcement.topic == 'D' %}
          <p> Topic: Philanthropy </p>
          {% elif announcement.topic == 'E' %}
          <p> Topic: Recruitment </p>
          {% elif announcement.topic == 'F' %}
          <p> Topic: Social </p>
          {% else %}
          <p> Topic: New Member </p>
          {% endif %}

          <!-- if to convert internal type codes to readable format -->
          {% if announcement.type == 'G' %}
          <p> Type: Normal </p>
          {% else %}
          <p> Type: <strong class=text-danger> URGENT </strong> </p>
          {% endif %}

          <p>Message: {{ announcement.message|linebreaksbr }}</p>

          <a class="btn btn-dark" href="{% url 'announcement:AnnouncementsView' %}">Back</a>
          <!-- if to check if the user that created the announcement is the one viewing it and allowing them to edit the post.
               request.user is comparing a User model to announcement.creator (which is also a User model) -->
          {% if request.user == announcement.creator %}
            <a class="btn btn-danger" href="{% url 'announcement:announcement_edit' pk=announcement.pk %}">Edit</a>
            <a class="btn btn-danger" href="{% url 'announcement:announcement_delete' pk=announcement.pk %}">Delete</a>
          {% endif %}
        </div>
      </div>


    </div>
    <hr>
    <div class="card">
      <h5 class="card-header">Comments</h5>
      <div class="card-body">
        {% for comment in announcement.comments.all %}
        <div class="card-text comment">
          <div class="date">{{ comment.created_date }}</div>
          <strong>{{ comment.author }}</strong>
          <p>{{ comment.text|linebreaks }}</p>
          <hr>
        </div>
        {% empty %}
        <p>No comments here yet :(</p>
        {% endfor %}
        <a class="btn btn-danger" href="{% url 'announcement:add_comment_to_announcement' pk=announcement.pk %}">Add comment</a>
      </div>
    </div>
    
{% endblock %}

GLMMS/announcement/templates/announcement/announcement_edit.html
<!-- 
Author: Jason Pulis
Styling: Mike Winkelmann

 -->

{# This template displays an edit form for editable fields of an announcement object. Requires a `AnnouncementForm` #}

{% extends 'common/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h2>New Announcement</h2>
    <form method="POST" class="post-form">
        {% csrf_token %}
        <div class="row">
            <div class="col-sm-6 col-lg-4">
                {{ form.type|as_crispy_field }}
            </div>
            <div class="col-sm-6 col-lg-4">
                {{ form.topic|as_crispy_field }}
            </div>
            <div class="col-sm-12 col-lg-8">
                {{ form.title|as_crispy_field }}
            </div>
            <div class="col-sm-12 col-lg-8">
                {{ form.message|as_crispy_field }}
            </div>
        </div>
        <a class="btn btn-dark" href="{% url 'announcement:AnnouncementsView' %}">Cancel</a>
        <button class="btn btn-danger" type="submit">Save</button>
    </form>
{% endblock %}

GLMMS/announcement/templates/announcement/announcement_search.html
<!-- 
Author: Jason Pulis
Styling: Mike Winkelmann

 -->

{# This template displays a list of all announcements. #}

{% extends "common/base.html" %}
{% load static %}

{% block content %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
{% load sorter %}


<h1>Announcements Search</h1>
<a class="btn btn-primary" href="{% url 'announcement:AnnouncementsView' %}">Back</a>
<a class="btn btn-danger" href="{% url 'announcement:announcement_new' %}">Create New</a>

<form method="get">
    {{ filter.form }} <!--"form rendering options" to change them i.e. filter.form.as_table is a table-->
    <button type="submit">Search</button>
</form>

<div class="row">
    {% for announcements in filter.qs %}
    <div class="col-sm-12 col-lg-6">
      <div class="card" style="margin-bottom: .25rem; margin-top: .25rem">
        {% if announcements.type == 'H' %}
        <h5 class="card-header">★ {{ announcements.title }} ★</h5>
        {% else %}
        <h5 class="card-header">{{ announcements.title }}</h5>
        {% endif %}
        <div class="card-body">
          <h5 class="card-title">{{ announcements.creator }}</h5>
          <p class="card-text">{{ announcements.dateAdded }}</p>
          <a href="{% url 'announcement:announcement_detail' pk=announcements.pk %}" class="btn btn-danger">Details</a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>


{% endblock %}

GLMMS/announcement/templates/announcement/announcement_view_all.html
<!-- 
Author: Jason Pulis
Styling: Mike Winkelmann

 -->

{# This template displays a list of all announcements. #}

{% extends "common/base.html" %}
{% load static %}

{% block content %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
{% load sorter %}


<h1>Announcements</h1>
<hr>
<a class="btn btn-danger" href="{% url 'announcement:announcement_new' %}">Create New</a>
<a class="btn btn-danger" href="{% url 'announcement:AnnouncementsViewSearch' %}">Search</a>

<div class="row">
    {% for announcements in announcements %}
    <div class="col-sm-12 col-lg-6">
      <div class="card" style="margin-bottom: .25rem; margin-top: .25rem">
        {% if announcements.type == 'H' %}
        <h5 class="card-header" style="background: #808080; color: white">{{ announcements.title }}</h5>
        <div class="card-body" style="background: #A9A9A9; color: white">
          <h5 class="card-title" >{{ announcements.creator }}</h5>
          <p class="card-text">
            {{ announcements.dateAdded }}
            <br>
            Comments: {{ announcements.comments.count }}
          </p>
          <a href="{% url 'announcement:announcement_detail' pk=announcements.pk %}" class="btn btn-danger">Details</a>
        </div>
        {% else %}
        <h5 class="card-header">{{ announcements.title }}</h5>
        <div class="card-body">
          <h5 class="card-title">{{ announcements.creator }}</h5>
          <p class="card-text">
            {{ announcements.dateAdded }}
            <br>
            Comments: {{ announcements.comments.count }}
          </p>
          <a href="{% url 'announcement:announcement_detail' pk=announcements.pk %}" class="btn btn-danger">Details</a>
        </div>
        {% endif %}
          
      </div>
    </div>
    {% endfor %}
    </div>

    <ul class="pagination">
        {% if announcements.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page=1">&laquo; First</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ announcements.previous_page_number }}">Previous</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link">&laquo; First</a>
        </li>
        <li class="page-item disabled">
            <a class="page-link">Previous</a>
        </li>    
        {% endif %}

        <li class="page-item">
            <a class="page-link disabled">Page {{ announcements.number }} of {{ announcements.paginator.num_pages }}</a>
        </li>

        {% if announcements.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ announcements.next_page_number }}">Next</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ announcements.paginator.num_pages }}">Last &raquo;</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link">Next</a>
        </li>
        <li class="page-item disabled">
            <a class="page-link">Last &raquo;</a>
        </li>
        {% endif %}
    </ul>


{% endblock %}