GLMMS/GLMMS_main/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

# Use include() to add URLS from the catalog application and authentication system
from django.urls import include

urlpatterns += [
    path('catalog/', include('catalog.urls')),
	path('member/', include('member.urls')),
	path('event/', include('event.urls')),
	path('announcement/', include('announcement.urls')),
]

# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
]

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

#add media file support
from . import settings as mysettings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(mysettings.MEDIA_URL, document_root=mysettings.MEDIA_ROOT)

GLMMS/event/urls.py
#Author: Christopher Whetsel

from django.urls import path

from . import views

app_name = 'event'
urlpatterns = [
    path('', views.events_view, name='events_view'),
    path('event/past/', views.past_events_view, name="past_events"),
    path('event/<int:pk>/', views.event_detail, name='event_detail'),
    path('event/new/', views.event_new, name='event_new'),
    path('event/<int:pk>/edit/', views.event_edit, name='event_edit'),
    path('event/<int:pk>/rsvp/', views.event_rsvp, name='event_rsvp'),
    path('event/<int:pk>/delete/', views.event_delete, name='event_delete'),
    path('event/<int:pk>/notify/', views.event_notify, name='event_notify'),
]

GLMMS/locallibrary/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

# Use include() to add URLS from the catalog application and authentication system
from django.urls import include

urlpatterns += [
    path('catalog/', include('catalog.urls')),
	path('member/', include('member.urls')),
	path('event/', include('event.urls')),
	path('announcement/', include('announcement.urls')),
]

# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
]

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

#add media file support
from . import settings as mysettings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
 
 
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(mysettings.MEDIA_URL, document_root=mysettings.MEDIA_ROOT)

GLMMS/member/urls.py
#Author: Christopher Whetsel

'''this file defines the mapping of urls to view functions. see views.py for the view definitions.'''
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'member'
urlpatterns = [
	path('search', views.search_index, name='search_index'),
	path('search/single/', views.single_search, name='single_search'),
	path('search/multi/', views.multi_search, name='multi_search'),
	path('search/job/', views.job_search, name='job_search'),
	path('search/position/', views.position_search, name='position_search'),
	path('search/organization/', views.org_search, name='organization_search'),
	path('profile/<int:pk>/', login_required(views.ProfileDetailView.as_view()), name='profile'),
	path('profile/edit/<int:profile_id>', views.edit_info, name='edit_profile'),
]

'''urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
	path('<int:pk>/', views.SingleDetailView.as_view(), name='single_detail'),
	path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
	path('<int:question_id>/vote/', views.vote, name='vote'),
]'''

GLMMS/member/forms.py
#Author: Christopher Whetsel

from django import forms
from django.contrib.auth.models import User

from .models import Profile

class SingleSearchForm(forms.Form):
	'''Form class for the single search view'''
	#get the data to populate the select forms with
	#create the model fields
	actives_choice = forms.ChoiceField(required=False, choices=[], label="Active Members")
	alumni_choice = forms.ChoiceField(required=False, choices=[], label="Alumni Members")
	newmembers_choice = forms.ChoiceField(required=False, choices=[], label="New Members")
	inactives_choice = forms.ChoiceField(required=False, choices=[], label="Inactive Members")
	def __init__(self, *args, **kwargs):
		super(SingleSearchForm, self).__init__(*args, **kwargs)
		BLANK='----'
		members = Profile.get_all_members_by_category(BLANK)
		self.fields['actives_choice'] = forms.ChoiceField(required=False, choices=members[Profile.ACTIVE], label="Active Members")
		self.fields['alumni_choice'] = forms.ChoiceField(required=False, choices=members[Profile.ALUMNI], label="Alumni Members")
		self.fields['newmembers_choice'] = forms.ChoiceField(required=False, choices=members[Profile.NEWMEMBER], label="New Members Members")
		self.fields['inactives_choice'] = forms.ChoiceField(required=False, choices=members[Profile.INACTIVE], label="Inactive Members")
	
class MultiSearchForm(forms.Form):
	'''Form class for the multi member search view'''
	#get the data to populate the select forms with
	#create the model fields
	status_choice = forms.ChoiceField()
	#fields = [(field.name, field.verbose_name) for field in Profile._meta.get_fields() if not isinstance(field, ManyToOneRel)]
	field_choice = forms.MultipleChoiceField()
	order_choice = forms.MultipleChoiceField()
	ALL_MEMBERS = '__all__'
	def __init__(self, *args, **kwargs):
		super(MultiSearchForm, self).__init__(*args, **kwargs)
		#fields to pick which collumns to search and how to sort
		#not in ('bio', 'photo', 'jobs', 'organizations', 'positions', 'pledge_father', 'cell_carrier_id')]
		dict_fields = Profile.get_printable_fields()
		fields = []
		for key, value in dict_fields.items():
			fields.append((key, value))
		statuses = list(Profile.STATUS)
		statuses.insert(0, (MultiSearchForm.ALL_MEMBERS, 'All Members'))
		self.fields['status_choice'] = forms.ChoiceField(required=True, choices=statuses, initial={MultiSearchForm.ALL_MEMBERS: 'Everything'}, label="Member Group to Search?")
		#multiple choice fields are a multipe select
		fields.insert(0,(MultiSearchForm.ALL_MEMBERS, 'Everything'))
		self.fields['field_choice'] = forms.MultipleChoiceField(required=True, choices=fields, initial=MultiSearchForm.ALL_MEMBERS, label="What information to display?")
		#remove everything option from the ordering cause that doesnt make sense
		fields.remove((MultiSearchForm.ALL_MEMBERS, 'Everything'))
		fields.insert(0,('user__username', 'Username'))
		fields.insert(1,('user__last_name', 'Last Name'))
		fields.insert(2,('user__first_name', 'First Name'))
		self.fields['order_choice'] = forms.MultipleChoiceField(required=True, choices=fields, initial='user__username', label="How to sort the results?")

class ProfileEditForm(forms.ModelForm):
	'''This class provides a profile edit form.'''
	class Meta:
		model = Profile
		fields = ['bio', 'phone', 'address', 'pledge_class', 'major', 'major2', 'emphasis', 'grad_semester', 'grad_year', 'shirt_size', 'member_status', 'linkedin_profile', 'cumulative_gpa', 'last_sem_gpa', 'last_update', 'birth_date', 'photo', 'pledge_father', 'cell_carrier_id']

class UserEditForm(forms.ModelForm):
	'''THis class provides an edit form for the user.'''
	class Meta:
		model = User
		fields = ['first_name', 'last_name', 'email']

GLMMS/member/views.py
#Author: Christopher Whetsel

'''The views for the member app.'''
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.views import generic
from django.utils import timezone
from django.contrib.auth.decorators import login_required
#from django.template import loader 

from django.contrib.auth.models import User
from django.core import serializers
from .models import Profile
from .forms import ProfileEditForm, MultiSearchForm, SingleSearchForm, UserEditForm


class ProfileDetailView(generic.DetailView):
	'''This is a detail view for the a profile'''
	model = Profile
	template_name = 'member/profile.html'

@login_required
def search_index(request):
	'''view returns a rendered template for search_index page'''
	return render(request, 'member/search_index.html')

@login_required
def single_search(request):
	'''View to return a form to search for a member's profile. Handles Get and Post'''
    #handle a search for a profile
	if request.method == 'POST':
		#create a form object from the request
		form = SingleSearchForm(request.POST)
		profile = None
		#validate input
		if form.is_valid():
			#check all the select boxes for a choice that isnt BLANK
			for key in form.cleaned_data:
				if form.cleaned_data[key]:
					#get the profile object sepcified by the user choice.
					profile = Profile.objects.get(pk=int(form.cleaned_data[key]))
					choices = Profile.get_printable_fields()
					#we dont want to show the linked in profile in the table because its in the profile highlight area
					del choices['linkedin_profile']
			if profile is not None:
				form = SingleSearchForm()
				return render(request, 'member/single_search.html', {'form': form, 'profile': profile})
			return render(request, 'member/single_search.html', {'form': form, 'error_message': "Please select a member from one of the lists!"})
    #handle a GET request for just the form
	else:
		#empty form
		form = SingleSearchForm()
	#return a page without a profile result
	return render(request, 'member/single_search.html', {'form': form})

@login_required
def edit_info(request, profile_id):
	'''view to return a page to edit a user's profile info. Handles GET and POST'''
	#get the requested profile, or if it cannot be found, return 404
	profile = get_object_or_404(Profile, pk=profile_id)
	#handle a request to edit the info
	if request.method == "POST":
		#create the forms from the user inputted data
		pro_form = ProfileEditForm(request.POST, request.FILES, instance=profile)
		user_form = UserEditForm(request.POST, instance=profile.user)
		#if the forms are valid, save the changes. 
		if pro_form.is_valid() and user_form.is_valid():
			profile = pro_form.save()
			user_form.save()
			#return success message and redirect to profile. 
			#TODO change to a redirect
			return render(request, 'member/profile.html', {'profile': profile, 'error_message': "Changes have been saved!"})
	#handle a reuest for a prepopulated form to edit using the logged in user
	else:
		pro_form = ProfileEditForm(instance=profile)
		user_form = UserEditForm(instance=profile.user)
	return render(request, 'member/member_edit_form.html', {'profile_form': pro_form, 'user_form': user_form})

@login_required
def multi_search(request):
	'''view to handle the GET and POST of the multi search page.'''
	#handle a search form submission
	if request.method == 'POST':
		#create the form from the the user submitted data
		form = MultiSearchForm(request.POST)
		#validate the form
		if form.is_valid():
			#get the choices from the form
			status = form.cleaned_data['status_choice']
			fields = form.cleaned_data['field_choice']
			order = form.cleaned_data['order_choice']
			print(order)
			# get the requested subset of users
			if status == MultiSearchForm.ALL_MEMBERS:
				results = Profile.objects.all().order_by(*order)
			else:
				results = Profile.objects.filter(member_status=status).order_by(*order)
			#get the list of fields the user wanted to see. 
			display_fields = []
			for key in Profile.get_printable_fields().keys():
				if MultiSearchForm.ALL_MEMBERS in fields:
					display_fields.append(key)
				else:
					display_fields = fields
			print(results)
			#print(display_fields)
			#have to serialize so we can loop through just these fields in the template 
			data = serializers.serialize( "python", results, fields=display_fields)
			#zip the profiles and the data to iterate over. could not figure out how to access specific items of the serialized object
			# have to put it in a list so that python will evaluate so we can get its length in the template. 
			results = list(zip(results, data))
			return render(request, 'member/multi_search.html', {'form': form, 'results': results, 'fields': display_fields}) 
	#return an empty form
	else:
		form = MultiSearchForm()
	return render(request, 'member/multi_search.html', {'form': form})

#TODO
@login_required
def position_search(request):
	return render(request, 'member/search_index.html')
#TODO
@login_required
def job_search(request):
	return render(request, 'member/search_index.html')
#TODO
@login_required
def org_search(request):
	return render(request, 'member/search_index.html')
	

GLMMS/member/templates/member/member_edit_form.html
<!--
Author: Christopher Whetsel
Formatting: Mike Winkelmann
-->

{# This template displays an edit form for editable fields of a profile object. Requires a `profile_form` and a `user_form` #}

{% extends "common/base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
{% if user.profile %}
{% if error_message %}<p><strong>{{ error_message }} </strong></p>{% endif %}

<h1>Member Edit Info</h1>
<hr>
<h4>Edit your information and click save:</h4>

<form action="{% url 'member:edit_profile' user.profile.id %}" method="POST" enctype='multipart/form-data'>
	{% csrf_token %}
	<div class="row">
		<div class="col-sm-12 col-lg-4">
			{{ user_form.first_name|as_crispy_field }}
		</div>
		<div class="col-sm-12 col-lg-4">
			{{ user_form.last_name|as_crispy_field }}
		</div>
		<div class="col-sm-12 col-lg-4">
			{{ user_form.email|as_crispy_field }}
		</div>
	</div>
	<div class="row">
		
		<div class="col-sm-12 col-lg-12">
			{{ profile_form.bio|as_crispy_field }}
		</div>
		<div class="col-sm-12 col-lg-4">
			{{ profile_form.phone|as_crispy_field }}
		</div>
		<div class="col-sm-12 col-lg-8">
			{{ profile_form.address|as_crispy_field }}
		</div>
		<div class="col-sm-12 col-lg-3">
			{{ profile_form.pledge_class|as_crispy_field }}
		</div>
		<div class="col-sm-12 col-lg-3">
			{{ profile_form.major|as_crispy_field }}
		</div>
		<div class="col-sm-12 col-lg-3">
			{{ profile_form.major2|as_crispy_field }}
		</div>
		<div class="col-sm-12 col-lg-3">
			{{ profile_form.emphasis|as_crispy_field }}
		</div>
		<div class="col-sm-12 col-lg-3">
			{{ profile_form.shirt_size|as_crispy_field }}
		</div>
		<div class="col-sm-12 col-lg-3">
			{{ profile_form.member_status|as_crispy_field }}
		</div>
		<div class="col-sm-12 col-lg-3">
			{{ profile_form.grad_semester|as_crispy_field }}
		</div>
		<div class="col-sm-12 col-lg-3">
			{{ profile_form.grad_year|as_crispy_field }}
		</div>
		<div class="col-sm-12 col-lg-12">
			{{ profile_form.linkedin_profile|as_crispy_field }}
		</div>
		<div class="col-sm-12 col-lg-3">
			{{ profile_form.cumulative_gpa|as_crispy_field }}
		</div>
		<div class="col-sm-12 col-lg-3">
			{{ profile_form.last_sem_gpa|as_crispy_field }}
		</div>
		<div class="col-sm-12 col-lg-3">
			{{ profile_form.last_update|as_crispy_field }}
		</div>
		<div class="col-sm-12 col-lg-3">
			{{ profile_form.birth_date|as_crispy_field }}
		</div>
		<div class="col-sm-12 col-lg-6">
			{{ profile_form.pledge_father|as_crispy_field }}
		</div>
		<div class="col-sm-12 col-lg-6">
			{{ profile_form.cell_carrier_id|as_crispy_field }}
		</div>
		<div class="col-sm-12 col-lg-12">
			{{ profile_form.photo|as_crispy_field }}
		</div>
	</div>
	<input class="btn btn-success" type="submit" value="Save">
</form>
<hr>
{% else %}
<p>You are not logged in or you have no profile</p>
{% endif %}

{% endblock %}

GLMMS/member/templates/member/multi_search.html
<!--
Author: Christopher Whetsel
Formatting: Mike Winkelmann
-->

{# This template displays the multiple member serach page.  #}

{% extends "common/base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
{% if error_message %}<p><strong>{{ error_message }} </strong></p>{% endif %}

<h1>Multi-Member Search</h1>
<hr>
<h4>Choose your search criteria from the dropdown lists below:</h4>
{% if error_message %}<p><strong>{{ error_message }} </strong></p>{% endif %}

<form action="{% url 'member:multi_search' %}" method="POST">
	{% csrf_token %}
	<div class="row">
		<div class="col-sm-12 col-lg-12">
			{{ form.status_choice|as_crispy_field }}
		</div>
		<div class="col-sm-6 col-lg-6">
			{{ form.field_choice|as_crispy_field }}
		</div>
		<div class="col-sm-6 col-lg-6">
			{{ form.order_choice|as_crispy_field }}
		</div>
		<div class="col-lg-4"></div>
	</div>
	<input class="btn btn-danger" type="submit" value="Search">
</form>
<hr>
{% if fields %}
{% include "member/print_table.html" %}
{% endif %}
 <!--
<ul>
{% for choice in quesiton.choice_set.all %}
	<li>{{ choice.choice_text }}<li>
{% endfor %}
</ul>
-->
{% endblock %}

GLMMS/member/templates/member/print_table.html
<!--
Author: Christopher Whetsel
Formatting: Mike Winkelmann
-->

{# this file will print a table containing the fields and values for each profile object given. The context needs to contain `fields` which is a list of verbose field names and results which is a zipped list of profiles and serialized profiles #}


{% load static %}
{% if results %}
<h1>Number of Results: {{ results|length }}</h1>
<div class="table-responsive">
    <table class="table table-bordered">
        <thead class="thead-light">
            <tr>
            <th scope="col">Username</th>
            <th scope="col">Name</th>
            <th scope="col">Email</th>
            {% for field_name in fields %}
                <th scope="col">{{ field_name }}</th>
            {% endfor %}
            </tr>
        </thead>
        {% for profile, data in results %}
        <tbody>
            <tr>
                <td scope="row">{{ profile.user.username }}</td>
                <td scope="row">{{ profile.user.first_name }} {{ profile.user.last_name }}</td>
                <td scope="row">{{ profile.user.email }}</td>
                {% for field, value in data.fields.items %}
                    <td scope="row">{{ value|default:"N/A" }}</td>
                {% endfor %}
            </tr>
        </tbody>
    {% endfor %}
    </table>
</div>
{% else %}
<h1>Number of Results: 0</h1>
{% endif %}

GLMMS/member/templates/member/profile.html
<!--
Author: Christopher Whetsel
Formatting: Mike Winkelmann
-->

{# This template is for the profile page. needs `profile` in the context #}

{% extends "common/base.html" %}
{% block content %}
    {% if user.profile %}
        {% include "member/single_detail.html" %}
        <a href="{% url 'member:edit_profile' user.profile.id %}" class="btn btn-danger">Edit Info</a>
    {% else %}
        <p>You are not logged in or you have no profile</p>
    {% endif %}
{% endblock %}

GLMMS/member/templates/member/profile_detail.html
<!--
Author: Christopher Whetsel
Formatting: Mike Winkelmann
-->

{# THIS FILE IS NOT USED CURRENTLY #}

{# {% block title %}{{ profile.user.first_name }} {{profile.user.last_name }}: Details {% endblock %} #}
{% block content %}
{% load static %}
{% if error_message %}<p class='error'><strong>{{ error_message }} </strong></p>{% endif %}

<hr>
<h1>{{ profile.user.first_name }} {{profile.user.last_name }}'s Profile</h1>
<div class="row justify-content-center">
<div class="col-4">
    {% if profile.photo %}
    <img src="{{ profile.photo.url }}" alt="profile picture" style="height:300px;max-width:300px;"/>
    {% else %}
    <img src="{% static '/member/images/coat.png' %}" alt="no profile picture" style="height:300px;max-width:300px;"/>
    {% endif %}
</div>
<div class="col-6">
   <h3>Bio</h3>
   <p>{{ profile.bio }} </p>
   <br>
   <h3>Email</h3>
   <p>{{ user.email }}</p>
   <br>
   <h4>LinkedIn Profile</h4>
   <a href="{{ profile.linkedin_profile }}" target="_blank">{{profile.linkedin_profile|default:"No profile"}}</a>
</div>
<div class="col-2"></div>
</div>

<hr>

<table class='table-bordered table-striped table-condensed cf'>
<thead>
        <th>Username</th>
    {% for name, value in profile.get_printable_fields_and_values %}
       <th>{{ name }}</th>
    {% endfor %}
   </thead>
   <tr>
        <td>{{ profile.user.username }}</td>
    {% for name, value in profile.get_printable_fields_and_values %}
       <td>{{ value|default:"N/A" }}</td>
    {% endfor %}
   </tr>
</table>
<!--
<ul>
{% for choice in quesiton.choice_set.all %}
   <li>{{ choice.choice_text }}<li>
{% endfor %}
</ul>
-->
{% endblock %} 

GLMMS/member/templates/member/search_index.html
<!--
Author: Christopher Whetsel
Formatting: Mike Winkelmann
-->

{# This template shows the index page for the search functions. This requires no centext #}

{% extends "common/base.html" %}
{# {% block title %} Member Search {% endblock %} #}

{% block content %}
<h1>Member Information Search Index</h1>
<hr>
<h4>Choose the type of search to perform</h4>
<div class="col-4 list-group">
	<a class="list-group-item list-group-item-action" href="{% url 'member:single_search'%}">Single Member Search</a>
	<a class="list-group-item list-group-item-action" href="{% url 'member:multi_search'%}">Multi-Member Search</a>
	<!--<a class="list-group-item list-group-item-action" href="{% url 'member:job_search'%}">Job Search</a>
	<a class="list-group-item list-group-item-action" href="{% url 'member:position_search'%}">Position Search</a>
	<a class="list-group-item list-group-item-action" href="{% url 'member:organization_search'%}">Organization Search</a>-->
</div>
{% endblock %}

GLMMS/member/templates/member/single_detail.html
<!--
Author: Christopher Whetsel
Formatting: Mike Winkelmann
-->

{# This template shows the profile for a single user. Include it in a template that has `profile` in the context #}

{% block content %}
{% load static %}
{% if error_message %}<p class='error'><strong>{{ error_message }} </strong></p>{% endif %}

<hr>
<h1>{{ profile.user.first_name }} {{profile.user.last_name }}'s Profile</h1>
<div class="row justify-content-center">
	<div class="col-sm-6 col-lg-4">
		{% if profile.photo %}
		<img src="{{ profile.photo.url }}" alt="profile picture" style="height:300px;max-width:300px;" />
		{% else %}
		<img src="{% static '/member/images/coat.png' %}" alt="no profile picture" style="height:300px;max-width:300px;" />
		{% endif %}
	</div>
	<div class="col-sm-6 col-lg-6">
		<h3>Biography</h3>
		<p>{{ profile.bio }}</p>
		<br>
		<h3>Email</h3>
		<p>{{ profile.user.email }}</p>
		<br>
		<h4>LinkedIn Profile</h4>
		<a href="{{ profile.linkedin_profile }}" target="_blank">{{profile.linkedin_profile|default:"No profile"}}</a>
	</div>
	<div class="col-sm-0 col-lg-2"></div>
</div>
<hr>
<table class='table-bordered table-striped table-condensed cf'>
	
</table>
<div class="table-responsive">
    <table class="table table-bordered">
		<thead class="thead-light">
			{% for name, value in profile.get_printable_fields_and_values %}
				<th scope="col">{{ name }}</th>
			{% endfor %}
		</thead>
		<tbody>
			<tr>
			{% for name, value in profile.get_printable_fields_and_values %}
				<td scope="row">{{ value|default:"N/A" }}</td>
			{% endfor %}
			</tr>
		</tbody>
    </table>
</div>
<!--

-->
{% endblock %}

GLMMS/member/templates/member/single_search.html
<!--
Author: Christopher Whetsel
Formatting: Mike Winkelmann
-->

{# This template is for the single member search page #}

{% extends "common/base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
{% if error_message %}<p><strong>{{ error_message }} </strong></p>{% endif %}

<h1>Single Member Search</h1>
<hr>
<h4>Choose from one dropdown list:</h4>
{% if error_message %}<p><strong>{{ error_message }} </strong></p>{% endif %}

<form action="{% url 'member:single_search' %}" method="POST">
	{% csrf_token %}
	<div class="row">
		<div class="col-lg-6">
			{{ form.actives_choice|as_crispy_field }}
		</div>
		<div class="col-lg-6">
			{{ form.alumni_choice|as_crispy_field }}
		</div>
		<div class="col-lg-6">
			{{ form.newmembers_choice|as_crispy_field }}
		</div>
		<div class="col-lg-6">
			{{ form.inactives_choice|as_crispy_field }}
		</div>
	</div>
	<input class="btn btn-danger" type="submit" value="Search">
</form>
{% if profile %}
{% include "member/single_detail.html" %}
{% endif %}
<!--
<ul>
{% for choice in quesiton.choice_set.all %}
	<li>{{ choice.choice_text }}<li>
{% endfor %}
</ul>
-->
{% endblock %}