GLMMS/GLMMS_main/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

# Use include() to add URLS from the catalog application and authentication system
from django.urls import include

urlpatterns += [
    path('catalog/', include('catalog.urls')),
	path('member/', include('member.urls')),
	path('event/', include('event.urls')),
	path('announcement/', include('announcement.urls')),
]

# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
]

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

#add media file support
from . import settings as mysettings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(mysettings.MEDIA_URL, document_root=mysettings.MEDIA_ROOT)

GLMMS/event/urls.py
#Author: Christopher Whetsel

from django.urls import path

from . import views

app_name = 'event'
urlpatterns = [
    path('', views.events_view, name='events_view'),
    path('event/past/', views.past_events_view, name="past_events"),
    path('event/<int:pk>/', views.event_detail, name='event_detail'),
    path('event/new/', views.event_new, name='event_new'),
    path('event/<int:pk>/edit/', views.event_edit, name='event_edit'),
    path('event/<int:pk>/rsvp/', views.event_rsvp, name='event_rsvp'),
    path('event/<int:pk>/delete/', views.event_delete, name='event_delete'),
    path('event/<int:pk>/notify/', views.event_notify, name='event_notify'),
]

GLMMS/locallibrary/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

# Use include() to add URLS from the catalog application and authentication system
from django.urls import include

urlpatterns += [
    path('catalog/', include('catalog.urls')),
	path('member/', include('member.urls')),
	path('event/', include('event.urls')),
	path('announcement/', include('announcement.urls')),
]

# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
]

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

#add media file support
from . import settings as mysettings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
 
 
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(mysettings.MEDIA_URL, document_root=mysettings.MEDIA_ROOT)

GLMMS/event/models.py
#Author: Christopher Whetsel


from django.db import models
from django.conf import settings
import datetime

from member.models import Profile
# Create your models here.
class Event(models.Model):
	GENERAL = 'A'
	SOCIAL = 'B'
	PROFESSIONAL = 'C'
	PHILANTHROPY = 'D'
	RECRUITMENT = 'E'
	NEWMEMBER = 'F'
	BROTHERHOOD = 'G'
	TOPICS = ((GENERAL, 'General'), (SOCIAL,'Social'), (PROFESSIONAL, 'Professional'), (PHILANTHROPY, 'Philanthropy'), (RECRUITMENT, 'Recruitment'), (NEWMEMBER, 'New Member'), (BROTHERHOOD,'Brotherhood Development'),)										#Profile
	creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	title = models.CharField(max_length=63)
	topic = models.CharField(max_length=1, choices=TOPICS, default=GENERAL)
	is_public = models.BooleanField(default=False)
	description = models.TextField()
	address = models.CharField(max_length=127)
	city = models.CharField(max_length=31)
	state = models.CharField(max_length=15)
	zipcode = models.CharField(max_length=5)
	dateAdded = models.DateTimeField(auto_now_add=True)
	start_time = models.DateTimeField()
	end_time = models.DateTimeField()
	rsvps = models.ManyToManyField(settings.AUTH_USER_MODEL, through='Event_RSVPs', related_name='member_rsvps')

	def __str__(self):
		return self.title

class Event_RSVPs(models.Model):
	'''table for the relation of profiles to orgs'''
	member = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	event = models.ForeignKey(Event, on_delete=models.CASCADE)

GLMMS/event/forms.py
#Author: Christopher Whetsel


from django import forms
from django.contrib.auth.models import User

from .models import Event

class SplitDateTimeWidget(forms.SplitDateTimeWidget):
    """
    A SplitDateTime Widget
    """
    template_name = 'admin/widgets/split_datetime.html'

    def __init__(self, attrs=None):
        widgets = [forms.widgets.DateInput(attrs={'type':'date'}), forms.widgets.TimeInput]
        # Note that we're calling MultiWidget, not SplitDateTimeWidget, because
        # we want to define widgets.
        forms.MultiWidget.__init__(self, widgets, attrs)

    def get_context(self, name, value, attrs):
        context = super().get_context(name, value, attrs)
        context['date_label'] = 'Date:'
        context['time_label'] = 'Time (24-hour hh:mm:ss):'
        return context

class EventForm(forms.ModelForm):
    '''This class provides an event creation form.'''
    class Meta: 
        model = Event
        fields = ['topic', 'title', 'description', 'start_time', 'end_time', 'is_public', 'address', 'city', 'state', 'zipcode']
        field_classes = {
            'start_time': forms.SplitDateTimeField,
            'end_time': forms.SplitDateTimeField, 
        }
        widgets = {
            'start_time': SplitDateTimeWidget(),
            'end_time': SplitDateTimeWidget(),
        }
        help_texts = {
            'is_public': ('Should this event be visible outside the Fraternity?'),
        }
        labels = {
            'is_public': ('Public Event?'),
        }

class NotificationForm(forms.Form):
    '''Form to create a notification'''
    subject = forms.CharField(label='Message Subject', max_length=127)
    message = forms.CharField(widget=forms.Textarea)
    #sender = forms.EmailField()
    type = forms.BooleanField(label="Check to send as a text message. Leave unchecked to send as an email.", required=False)

GLMMS/event/views.py
#Author: Christopher Whetsel

from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.views import generic
from django.utils import timezone
from django import forms
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.core.mail import send_mail, EmailMessage

from .models import Event, Event_RSVPs
from .forms import EventForm, NotificationForm

from datetime import datetime

# Create your views here.

@login_required
def events_view(request):
    '''View to handle the diaplyo f all events happening in the future '''
    today = datetime.now().date()
    events_list = Event.objects.filter(start_time__gte=today).order_by('start_time')
    paginator = Paginator(events_list, 6) # Show 5 events per page

    page = request.GET.get('page')
    events = paginator.get_page(page)
    return render(request, 'event/event_view_all.html', {'events': events, 'is_past': False})

@login_required
def past_events_view(request):
    '''View to handle the displaying of past events'''
    today = datetime.now().date()
    events_list = Event.objects.filter(start_time__lt=today).order_by('start_time')
    paginator = Paginator(events_list, 6) # Show 5 events per page

    page = request.GET.get('page')
    events = paginator.get_page(page)
    return render(request, 'event/event_view_all.html', {'events': events, 'is_past': True})

@login_required
def event_detail(request, pk):
    '''View to show the full details of an event'''
    event = get_object_or_404(Event, pk=pk)
    rsvps = Event_RSVPs.objects.filter(event=event).order_by('member__username')
    num_rsvps = rsvps.count()
    form = NotificationForm()
    return render(request, 'event/event_detail.html', {'event': event, 'num_rsvps':num_rsvps, 'rsvps': rsvps, 'form': form})

@login_required
def event_new(request):
    '''View to handle to the creation of a new event'''
    if request.method == "POST":
        form = EventForm(request.POST)
        if form.is_valid():
            event = form.save(commit=False)
            event.creator = request.user
            #post.dateAdded = timezone.now()
            event.save()
            return redirect('event:event_detail', pk=event.pk)
    else:
        form = EventForm()
    return render(request, 'event/event_edit.html', {'form': form})

@login_required
def event_edit(request, pk):
    '''View to handle the editting of an event'''
    event = get_object_or_404(Event, pk=pk)
    if request.method == "POST":
        form = EventForm(request.POST, instance=event)
        if form.is_valid():
            event = form.save(commit=False)
            event.creator = request.user
            event.dateAdded = timezone.now()
            event.save()
            return redirect('event:event_detail', pk=event.pk)
    else:
        form = EventForm(instance=event)
    return render(request, 'event/event_edit.html', {'event': event, 'form': form})

@login_required
def event_rsvp(request, pk):
    '''View that lets a user rsvp to an event once'''
    event = get_object_or_404(Event, pk=pk)
    if Event_RSVPs.objects.filter(event=event, member=request.user).count() == 0:
        Event_RSVPs.objects.create(event=event, member=request.user)
        messages.add_message(request, messages.INFO, "RSVP Successful!")
    else: 
        messages.add_message(request, messages.INFO, "You have already RSVP'ed")
    return redirect('event:event_detail', pk=pk)

@login_required
def event_delete(request, pk):
    '''View that allows the creator of an event to delete it'''
    event = get_object_or_404(Event, pk=pk)
    if request.user == event.creator:
        Event.objects.filter(pk=pk).delete()
        messages.add_message(request, messages.INFO, "Event Deleted.")
    else: 
        messages.add_message(request, messages.INFO, "You cannot delete an event you did not create.")
    return redirect('event:events_view')

@login_required
def event_notify(request, pk):
    '''View that lets the user send a message to users that have rsvped to their event'''
    event = get_object_or_404(Event, pk=pk)
    if request.method == "POST":
        if request.user == event.creator:
            form = NotificationForm(request.POST)
            if form.is_valid():
                subject = form.cleaned_data['subject']
                message = form.cleaned_data['message'] + "\r\n\r\nSent by " + event.creator.first_name + " " + event.creator.last_name
                sender = "notifications@spdmizzou.org"
                reply_to = [event.creator.email]

                recipients = []
                for rsvp in Event_RSVPs.objects.filter(event=event):
                    #send an email
                    if form.cleaned_data['type'] is False:
                        recipients.append(rsvp.member.email)  
                    #send a text                          
                    elif form.cleaned_data['type'] is True:
                        recipients.append(rsvp.member.profile.phone + "@" + rsvp.member.profile.cell_carrier_id.sms_address)
                email = EmailMessage(subject, message, sender, recipients, reply_to=reply_to)
                email.send()
                #send_mail(subject, message, sender, recipients)
                messages.add_message(request, messages.INFO, "Message sent!")
        else:
            messages.add_message(request, messages.INFO, "Only the creator is allowed to send nofications.")
    return redirect('event:event_detail', pk=pk)

GLMMS/event/templates/event/event_detail.html
<!--
Author: Christopher Whetsel
Formatting: Mike Winkelmann
-->

{# This template displays a detailed view of a selected event. #}

{% extends 'common/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
  {% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
  {% endif %}
    <div class="card">
      <h2 class="card-header">{{ event.title }}</h2>
      <div class="card-body">
        <h5 class="class-title">
            {% if event.topic == 'A' %}
            General Event 
            {% elif event.topic == 'B' %}
            Social Event 
            {% elif event.topic == 'C' %}
            Professional Event 
            {% elif event.topic == 'D' %}
            Philanthropy Event 
            {% elif event.topic == 'E' %}
            Recruitment Event 
            {% elif event.topic == 'F' %}
            Social Event 
            {% elif event.topic == 'G' %}
            Brotherhood Development Event
            {% else %}
            New Member Event 
            {% endif %}
            from {{ event.start_time }} to {{ event.end_time }}
        </h5>
        <div class="class-text">
          <p>{{ event.description|linebreaksbr }}</p>
          
          <!-- if to check if the user that created the event is the one viewing it and allowing them to edit the post.
               request.user is comparing a User model to event.creator (which is also a User model) -->
          <p>{{ num_rsvps }} Brothers are attending </p>
          <p class="collapse" id="collapseRSVP"> 
            {% for rsvp in rsvps %}
              {% if rsvp.member.first_name and rsvp.member.last_name %}
                {{ rsvp.member.first_name }} {{ rsvp.member.last_name }}, 
              {% else %}
                {{ rsvp.member.username }}
              {% endif %}
            {% endfor %}
          </p>
          <p>Location: {{ event.address }}, {{ event.city }}, {{ event.state }} {{ event.zipcode }}</p>
          <p>Created by {{ event.creator }} on {{ event.dateAdded }}</p>
            <a class="btn btn-dark" href="{% url 'event:events_view' %}">Back</a>
            <a class="btn btn-danger" href="{% url 'event:event_rsvp' pk=event.pk %}">RSVP to Event</a>
            <button class="btn btn-danger" type="button" data-toggle="collapse" data-target="#collapseRSVP"  {% if num_rsvps == 0 %} disabled {% endif %}>Show RSVPs</button>
          {% if request.user == event.creator %}
            <br><br>
            <a class="btn btn-danger" href="{% url 'event:event_edit' pk=event.pk %}">Edit</a>
            <a class="btn btn-danger" href="{% url 'event:event_delete' pk=event.pk %}">Delete</a>
            <a class="btn btn-danger" data-toggle="collapse" href="#collapseNotify" role="button">Notify RSVPs</a>
          {% endif %}
          </div>
      </div>
      <div class="collapse" id="collapseNotify">
        <div class="card">
          <h2 class="card-header">Create your Message</h2>
          <div class="card-body">
            <form action="{% url 'event:event_notify' pk=event.pk %}" method="POST" class="post-form">
              {% csrf_token %}
              <div class="row">
                <div class="col-sm-12 col-lg-8">
                    {{ form.subject|as_crispy_field }}
                </div>
                <div class="col-sm-12 col-lg-8">
                    {{ form.message|as_crispy_field }}
                </div>
                <div class="col-sm-12 col-lg-8">
                    {{ form.type|as_crispy_field }}
                </div>
              </div>
              <button class="btn btn-danger" type="submit">Send Message</button>
            </form>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

GLMMS/event/templates/event/event_edit.html
<!--
Author: Christopher Whetsel
Formatting: Mike Winkelmann
-->

{# This template displays an edit form for editable fields of an event object. Requires a `EventForm` #}

{% extends 'common/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h2>New Event</h2>
    <form method="POST" class="post-form">
        {% csrf_token %}
        <div class="row">
            <div class="col-sm-12 col-lg-8">
                {{ form.topic|as_crispy_field }}
            </div>
            <div class="col-sm-12 col-lg-8">
                {{ form.title|as_crispy_field }}
            </div>
            <div class="col-sm-12 col-lg-8">
                {{ form.description|as_crispy_field }}
            </div>
            <div class="col-sm-12 col-lg-12"></div>
            <div class="col-sm-6 col-lg-4">
                {{ form.start_time|as_crispy_field }}
            </div>
            <div class="col-sm-6 col-lg-4">
                {{ form.end_time|as_crispy_field }}
            </div>
            <div class="col-sm-8 col-lg-5">
                {{ form.address|as_crispy_field }}
            </div>
            <div class="col-sm-4 col-lg-3">
                {{ form.city|as_crispy_field }}
            </div>
            <div class="col-sm-12 col-lg-12"></div>
            <div class="col-sm-6 col-lg-4">
                {{ form.state|as_crispy_field }}
            </div>
            <div class="col-sm-3 col-lg-2">
                {{ form.zipcode|as_crispy_field }}
            </div>
            <div class="col-sm-3 col-lg-2">
                {{ form.is_public|as_crispy_field }}
            </div>
        </div>
        <button class="btn btn-dark" type="submit">Save</button>
        {% if event %}
            <a href="{% url 'event:event_detail' pk=event.pk %}" class="btn btn-danger">Cancel</a>
        {% else %}
            <a href="{% url 'event:events_view' %}" class="btn btn-danger">Cancel</a>
        {% endif %}
    </form>
{% endblock %}

GLMMS/event/templates/event/event_view_all.html
<!--
Author: Christopher Whetsel
Formatting: Mike Winkelmann
-->

{# This template displays a list of all events. #}

{% extends "common/base.html" %}
{% load static %}

{% block content %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
{% load sorter %}

<h1>Events</h1>
<hr>
<a class="btn btn-danger" href="{% url 'event:event_new' %}">Create New</a>
{% if is_past %}
    <a class="btn btn-danger" href="{% url 'event:events_view' %}">View Current Events</a>
{% else %}
    <a class="btn btn-dark" href="{% url 'event:past_events' %}">View Past Events</a>
{% endif %}
<div class="row">
    {% for events in events %}
    <div class="col-sm-12 col-lg-6">
      <div class="card" style="margin-bottom: .25rem; margin-top: .25rem">
        {% if events.is_public == True %}
        <h5 class="card-header">{{ events.title }}</h5>
        <div class="card-body">
          <h5 class="card-title">
            {% if events.topic == 'A' %}
            General Event
            {% elif events.topic == 'B' %}
            Social Event
            {% elif events.topic == 'C' %}
            Professional Event
            {% elif events.topic == 'D' %}
            Philanthropy Event
            {% elif events.topic == 'E' %}
            Recruitment Event
            {% elif events.topic == 'F' %}
            Social Event
            {% elif events.topic == 'G' %}
            Brotherhood Development Event
            {% else %}
            New Member Event
            {% endif %}
          </h5>
          <p class="card-text">Starts: {{ events.start_time }}</p>
          <p class="card-text">Ends: {{ events.end_time }}</p>
          <a href="{% url 'event:event_detail' pk=events.pk %}" class="btn btn-danger">Details</a>
        </div>
        {% else %}
        <h5 class="card-header" style="background: #808080; color: white">{{ events.title }}</h5>
        <div class="card-body" style="background: #A9A9A9; color: white">
          <h5 class="card-title">
            {% if events.topic == 'A' %}
            General Event
            {% elif events.topic == 'B' %}
            Social Event
            {% elif events.topic == 'C' %}
            Professional Event
            {% elif events.topic == 'D' %}
            Philanthropy Event
            {% elif events.topic == 'E' %}
            Recruitment Event
            {% elif events.topic == 'F' %}
            Social Event
            {% elif events.topic == 'G' %}
            Brotherhood Development Event
            {% else %}
            New Member Event
            {% endif %}
          </h5>
          <p class="card-text">Starts: {{ events.start_time }}</p>
          <p class="card-text">Ends: {{ events.end_time }}</p>
          <a href="{% url 'event:event_detail' pk=events.pk %}" class="btn btn-danger">Details</a>
        </div>
        {% endif %}
      </div>
    </div>
    {% endfor %}
  </div>

  <ul class="pagination">
      {% if events.has_previous %}
      <li class="page-item">
          <a class="page-link" href="?page=1">&laquo; First</a>
      </li>
      <li class="page-item">
          <a class="page-link" href="?page={{ events.previous_page_number }}">Previous</a>
      </li>
      {% else %}
      <li class="page-item disabled">
          <a class="page-link">&laquo; First</a>
      </li>
      <li class="page-item disabled">
          <a class="page-link">Previous</a>
      </li>    
      {% endif %}

      <li class="page-item">
          <a class="page-link disabled">Page {{ events.number }} of {{ events.paginator.num_pages }}</a>
      </li>

      {% if events.has_next %}
      <li class="page-item">
          <a class="page-link" href="?page={{ events.next_page_number }}">Next</a>
      </li>
      <li class="page-item">
          <a class="page-link" href="?page={{ events.paginator.num_pages }}">Last &raquo;</a>
      </li>
      {% else %}
      <li class="page-item disabled">
          <a class="page-link">Next</a>
      </li>
      <li class="page-item disabled">
          <a class="page-link">Last &raquo;</a>
      </li>
      {% endif %}
  </ul>


{% endblock %}